language: python
python:
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- coverage run --source ./ --omit setup.py -m unittest discover tst/
- coverage report -m
